cookie_message: Ce site utilise des cookies pour vous garantir la meilleure expérience sur notre site.
cookie_dismiss: J'ai compris!
cookie_link: Plus d'information or opt out
app_name: Web Opac App
title_photo: photo de couverture
links: Liens
link_imprint: Mehtions légales
link_privacy: Vie privée
link_app_play: Appli à Google Play
link_github: GitHub
link_twitter: Twitter