cookie_message: Diese Website nutzt Cookies um Ihr Nutzungserlebnis zu verbessern.
cookie_dismiss: Verstanden!
cookie_link: Mehr Infos und Opt-Out
app_name: Web Opac App
title_photo: Titelfoto
links: Links
link_imprint: Impressum
link_privacy: Datenschutz
link_app_play: App bei Google Play
link_github: GitHub
link_twitter: Twitter
link_support: Support
