cookie_message: This website uses cookies to ensure you get the best experience on our website.
cookie_dismiss: Got it!
cookie_link: Learn more or opt out
app_name: Web Opac App
title_photo: title photo
links: Links
link_imprint: Imprint
link_privacy: Privacy
link_app_play: App on Google Play
link_github: GitHub
link_twitter: Twitter
link_support: Support
